### ISSUE TITLE
Can CNVnator be installed on OS X? 

### ISSUE THREAD

**Issue by yoyohashao** [abyzovlab/CNVnator#60]
Hello I am a Mac user (10.12.4) and I wanna try CNVnator. I am having trouble with compiling and connecting to yeppp.info. I just need to make sure that I am not doing all this in vain. If CNVnator can only be installed on Linux, I am happy to give up ;) Otherwise, I will keep trying. Thanks

**Comment by abyzov** [comment]
Hi,
I myself regularly use CNVnator on Mac OS X 10.10.5.  Don’t see a reason why it shouldn’t work on 10.12.4

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by yoyohashao** [comment]
Dear Alexej,
After installing all the pre-requisites, I still got the error like : 

__make OMP=no
Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/include      -Isamtools -Isamtools/htslib-1.3.1 -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:14:
./HisMaker.hh:11:10: fatal error: 'TFrame.h' file not found
#include <TFrame.h>
         ^
1 error generated._
make: *** [obj/cnvnator.o] Error 1_

Could you tell me what goes wrong? Thanks a ton

**Comment by abyzov** [comment]
Hi,
looks like you don’t have ROOTSYS variable set up.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
