### ISSUE TITLE
Compiling CNVnator 0.3.2. Error when linking: undefined reference to `TString::TString

### ISSUE THREAD

**Issue by lindenb** [abyzovlab/CNVnator#31]
Hi,
I'm trying to compile CNVnator with root-6.06 but there is a problem when linking. Here is the makefile trace:

```
$ g++ --version
g++ (GCC) 5.2.0

$ echo ${ROOTSYS}
/ccc/products/root-6.06.06/default
```

```
$ make SAMDIR=/ccc/work/cont007/fg0019/lindenbp/packages/samtools HTSDIR=/ccc/work/cont007/fg0019/lindenbp/packages/htslib  -B
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c cnvnator.cpp -o obj/cnvnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c EXOnator.cpp -o obj/EXOnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c HisMaker.cpp -o obj/HisMaker.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c AliParser.cpp -o obj/AliParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c Genotyper.cpp -o obj/Genotyper.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c Interval.cpp -o obj/Interval.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/ccc/products/root-6.06.06/default/include      -I/ccc/work/cont007/fg0019/lindenbp/packages/samtools -I/ccc/work/cont007/fg0019/lindenbp/packages/htslib -c Genome.cpp -o obj/Genome.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o /ccc/work/cont007/fg0019/lindenbp/packages/samtools/libbam.a /ccc/work/cont007/fg0019/lindenbp/packages/htslib/libhts.a -lz -L/ccc/products/root-6.06.06/default/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Genome*)':
HisMaker.cpp:(.text+0x4280): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::pe_for_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, double, double)':
HisMaker.cpp:(.text+0x810a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, Genome*)':
HisMaker.cpp:(.text+0xa86a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::generateView(TString, int, int, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0xb903): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xbd5e): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xc723): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::view(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xd4b2): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::genotype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xda50): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::eval(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0x11da1): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::produceHistogramsNew(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x1334b): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::mergeTrees(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x15c71): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::callSVs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool, bool)':
HisMaker.cpp:(.text+0x168e7): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x1696f): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x16a06): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o:HisMaker.cpp:(.text+0x16a94): more undefined references to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'cnvnator' failed
```

can you please help me ?
thanks.

**Comment by lindenb** [comment]
my bad, I changed the C++ compiler and everything was find.
Thanks

**Comment by abyzov** [comment]
Glad to hear this!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jiadong324** [comment]
@lindenb Could you please tell me which g++ version are you using to solve your problem? I am having the same problem and I use g++47

**Comment by lindenb** [comment]
@jiadong324 it worked with  4.8.1

**Comment by jiadong324** [comment]
@lindenb thanks for your reply. I finally get it done by compiling root-5.34.09 with CNVnator v0.2.7.

**Comment by abyzov** [comment]
Hi,
glad to here is works now! Sorry, for late reply.

On personal Mac I’m using the following
>g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

On cluster I’m using
>g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Both root v5 and v6 are fine on each system.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
